apiVersion: v1
kind: Service
metadata:
  name: idtdb
  namespace: company-source
spec:
  selector:
    app: idtdb
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30014
  type: NodePort
