apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
  namespace: idt
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi