apiVersion: v1
kind: Service
metadata:
  name: idtdocumentdb
  namespace: idt
spec:
  selector:
    app: idtdocumentdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30011
  type: NodePort